apiVersion: batch/v1beta1
kind: CronJob
metadata:
  namespace: public-api
  name: weibo-cookie-renewer
  labels:
    app: weibo-cookie-renewer
spec:
  schedule: "30 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: weibo-cookie-renewer
        spec:
          imagePullSecrets:
            - name: registry-secret
          containers:
            - name: weibo-cookie-renewer
              image: __IMAGE_FULL_NAME__
              imagePullPolicy: Always
              env:
              - name: APP_SENTRYDSN
                value: __SENTRY_DSN__
              - name: APP_REDIS_ADDRESS
                value: redis:6379
              - name: APP_REDIS_PREFIX
                value: __REDIS_PREFIX__
          restartPolicy: OnFailure
